kind = "web"
  previewPath = "/"
  title = "DokMart - Documents Numériques"
  version = "1.0.0"
  id = "artifacts/dokmart"
  router = "path"

  [[integratedSkills]]
  name = "react-vite"
  version = "1.0.0"

  [[services]]
  name = "web"
  paths = [ "/" ]
  localPort = 23718

  [services.development]
  run = "pnpm --filter @workspace/dokmart run dev"

  [services.production]
  build = [ "pnpm", "--filter", "@workspace/dokmart", "run", "build" ]
  publicDir = "artifacts/dokmart/dist/public"
  serve = "static"

  [[services.production.rewrites]]
  from = "/*"
  to = "/index.html"

  [services.env]
  PORT = "23718"
  BASE_PATH = "/"
  